[package]
name = "stl2thumbnail"
version = "1.0.1"
authors = ["Paul <krepa098@gmail.com>"]
edition = "2018"
build = "build.rs"

[lib]
path = "src/lib.rs"
crate-type = ["lib", "staticlib", "cdylib"]

[[bin]]
name = "stl2thumbnail"
path = "src/main.rs"

[dependencies]
clap = "2.34.0"
png = "0.17.11"
gif = "0.13.1"
glm = { package = "nalgebra-glm", version = "0.18.0" }
scan_fmt = "0.2.6"
anyhow = "1.0"
byteorder = "1.4"

[build-dependencies]
cbindgen = "0.26.0"

#[profile.release]
#debug = true

#[profile.release]
#panic = "abort"
