name: archlinux makepkg

on:
    push:
      branches: [ master, cicd ]
    pull_request:
      branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                fetch-tags: true
                fetch-depth: 0

            - uses: docker/setup-buildx-action@v3
              with:
                install: true

            - run: docker build --platform=linux/amd64 -o . .

            - uses: actions/upload-artifact@v4
              with:
                name: archlinux pkg
                path: stl2thumbnail-*.tar.zst

            - uses: actions/upload-artifact@v4
              with:
                name: ubuntu deb
                path: stl2thumbnail-*.deb