name: arch pkg

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: setup buildx
              uses: docker/setup-buildx-action@v3

            - run: docker build --platform=linux/amd64 -o . .
