name: archlinux makepkg

on:
    push:
      branches: [ master, cicd ]
    pull_request:
      branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: docker/setup-buildx-action@v3
              with:
                install: true

            - run: docker build --platform=linux/amd64 -o . .

            - uses: actions/upload-artifact@v4
              with:
                name: stl2thumbnail-git.pkg.tar.zst
                path: stl2thumbnail-git.pkg.tar.zst

            - uses: actions/upload-artifact@v4
              with:
                name: stl2thumbnail-kde-git.pkg.tar.zst
                path: stl2thumbnail-kde-git.pkg.tar.zst