name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build
      run: cargo build --verbose
      working-directory: ${{ github.workspace }}/stl2thumbnail_rs
      
    - name: Run tests
      run: cargo test --verbose
      working-directory: ${{ github.workspace }}/stl2thumbnail_rs
