name: win32 installer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # build COM library
      - name: com library
        run: cargo build --release
        working-directory: ${{ github.workspace }}/desktop_integration/win32
      
      # copy COM library
      - run: cp ${{ github.workspace }}/desktop_integration/win32/target/release/stl2thumbnail_win32.dll ${{ github.workspace }}/dist/NSIS

      # create nullsoft installer
      - name: Create NSIS installer
        uses: joncloud/makensis-action@v3.3
        with:
          script-file: ${{ github.workspace }}/dist/NSIS/install.nsi

      # artifact
      - uses: actions/upload-artifact@v4
        with:
          name: Installer.exe
          path: ${{ github.workspace }}/dist/NSIS/Installer.exe
