name: win32 deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # build COM library
      - name: com library
        run: cargo build --release
        uses: dtolnay/rust-toolchain@stable
        working-directory: ${{ github.workspace }}/desktop_integration/win32
      
      # copy server.dll
      - name: dll copy
        run: cp ${{ github.workspace }}/desktop_integration/win32/target/release/stl2thumbnail.dll ${{ github.workspace }}/dist/NSIS
          
      # create nullsoft installer
      - name: Create nsis installer
        uses: joncloud/makensis-action@v3.3
        with:
          script-file: ${{ github.workspace }}/dist/NSIS/install.nsi

      # artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Installer.exe
          path: ${{ github.workspace }}/dist/NSIS/Installer.exe
